apiVersion: v1
kind: Service
metadata:
  name: {{ template "learn-database.fullname" . }}
  labels:
    app: {{ template "learn-database.name" . }}
    chart: {{ template "learn-database.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "learn-database.name" . }}
    release: {{ .Release.Name }}
